### ISSUE TITLE
Handling (or more helpful exception) of missing EBML element

### ISSUE THREAD

**Issue by tgipsonMIDE** [MideTechnology/ebmlite#40]
During xml2ebml conversion, it appears the document must contain (begin with?) an <EBML></EBML> element as a child of <MideDocument />. The element can be empty, as above, but if it is missing, this results in nonobvious error messages that differ between Python 2 and 3.

Test document:
```xml
<?xml version="1.0" encoding="utf-8"?>
<MideDocument>
	<!--<EBML>
	</EBML> -->
	<CalibrationList>
	</CalibrationList>
</MideDocument>
```
Python 3:

```
(base) C:\Users\timmay\Desktop\work\mide_simplicity_v4_workspace\CotF-sensor-CorBus\src>python C:\Users\timmay\Desktop\work\CotF\ebmlite\ebmlite\util.py -o sensor-canned-metadata.ebml -c xml2ebml test.xml mide_ide.xml

Traceback (most recent call last):
  File "C:\Users\timmay\Desktop\work\CotF\ebmlite\ebmlite\util.py", line 426, in <module>
    xml2ebml(args.input, out, schema)  # , sizeLength=4, headers=True, unknown=True)
  File "C:\Users\timmay\Desktop\work\CotF\ebmlite\ebmlite\util.py", line 276, in xml2ebml
    ebmlFile.write(cls.encodePayload(cls._createHeaders()))
TypeError: a bytes-like object is required, not 'str'
```

Python 2:
```
(py2) C:\Users\timmay\Desktop\work\mide_simplicity_v4_workspace\CotF-sensor-CorBus\src>python C:\Users\timmay\Desktop\work\CotF\ebmlite\ebmlite\util.py -o sensor-canned-metadata.ebml -c xml2ebml test.xml mide_ide.xml

Traceback (most recent call last):
  File "C:\Users\timmay\Desktop\work\CotF\ebmlite\ebmlite\util.py", line 426, in <module>
    xml2ebml(args.input, out, schema)  # , sizeLength=4, headers=True, unknown=True)
  File "C:\Users\timmay\Desktop\work\CotF\ebmlite\ebmlite\util.py", line 276, in xml2ebml
    ebmlFile.write(cls.encodePayload(cls._createHeaders()))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-4: ordinal not in range(128)
```

**Comment by pscheidler** [comment]
Just tried this and it appears to work. Note that with latest ebmlite the command is
`python -m ebmlite.tools.xml2ebml -o sensor-canned-metadata.ebml -c test.xml mide_ide.xml`
